# Generated by Django 4.2.1 on 2023-07-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0002_list_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': {'List'}, 'verbose_name_plural': {'List'}},
        ),
    ]
