# Generated by Django 4.2.1 on 2023-07-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0003_alter_list_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='Date',
        ),
    ]
